### ISSUE TITLE
Discount pot

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#109]
Can you please add a discount code which allows a guest to have a certain amount of credit (discount pot) that they can use towards multiple events that cost different amounts. So they could pay £20 and when they book any event the discount amount will be the full cost of any event they book, and then the discount code still has the remaining credit? So I would need to be able to specify the total credit available over an unspecified number of bookings, rather than Value and Max Usage.

**Comment by liedekef** [comment]
This is not as easy as it sounds ... since an event/membership can have more than one discount code, a booking can have it too. So, to be abe to track, I would need to keep the amount applied per discount id per booking/member (and not just the sum), and take into account cancellations too ...
For now, moving this to "funding required"

**Comment by TimB111** [comment]
I see.. How much funding would be required?

**Comment by liedekef** [comment]
Please contact me in private on franky [at] e-dynamics.be for a quote

**Comment by liedekef** [comment]
no reaction on quote, so closing
