### ISSUE TITLE
Printable booking title and comments missing

### ISSUE THREAD

**Issue by BudoAsahi** [liedekef/events-made-easy#14]
Hi Franky,
I updated to 2.3.37 a couple of days ago and just noticed on booking_printable the following is missing: 

- event-title
- respcomment, although col-heading is visible ("reactie")

Groetjes, 
Dionne

**Comment by liedekef** [comment]
Hi, 

both are already fixed in the code, I'm testing some other things and will release later this weekend.
The title fix is here:
https://github.com/liedekef/events-made-easy/commit/085f8364d6d2fe98dbe5e5a149367c6140ef3c8a#diff-a52cb577693531f9d8e56f4aaf4a316a1020ad964238f3e8c47ecccb997ca30b
And the comment fix:
https://github.com/liedekef/events-made-easy/commit/9e7e58a049148664fd9cbb94b797e44083d6b42f
