### ISSUE TITLE
Multi-booking emails not working properly

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [liedekef/events-made-easy#36]
**Describe the bug**
I set up a recurring event with Multi-seat & Multi-price. Then I followed the documentation to make a Multi-booking form with the appropriate header, body, footer. Confirmation email required is also turned on. Everything displayed properly on the website. Nothing is changed in the "RSVP Email format settings". After registering for the recurring event, an email requiring confirmation is received. However, after confirmation, only 1 email stating that the "Registration for 'Recurring Event' confirmed" is received. The body of the email only stated that "You have successfully registered 1 seat(s) for 'Recurring Event'." There is no mention of the multi-booked dates and seats.

Furthermore, after deleting the registration, multiple event deletion emails are received with the heading "Registration for 'Test Event' deleted" with the body stating "Your request to register 1 seat(s) for 'Recurring Event' has been deleted." As I set the recurring event to have 5 sessions, the system sent me 5 deletion emails.

**To Reproduce**
1. Set up recurring event
2. Set up multi-price & multi-seat
3. Set up multi-booking form
4. Test register for event
5. See error

**Expected behavior**
There should be an email stating the multi-booked dates & seats in the body. Also, all deletions in a recurring event should be consolidated into 1 email instead of sending multiple ones, regardless if 1 or all the sessions in the recurring event is deleted.

**Additional context**
I believe this issue was supposedly resolved months ago but it is appearing again.

**Screenshots**
Registration form
![Screenshot 2023-01-24 at 09-41-58 Test Event](https://user-images.githubusercontent.com/101639308/214195878-884f5c74-c760-4e52-aa05-9bbd2629f2ef.png)

![Screenshot_20230124-093349](https://user-images.githubusercontent.com/101639308/214195386-32682f81-8c6b-4e7e-a6d3-500d72677fd1.png)

![Screenshot_20230124-093331](https://user-images.githubusercontent.com/101639308/214195391-d2d888ec-e6f1-49e0-b87d-a01a0f5c60c6.png)

![Screenshot_20230124-093359](https://user-images.githubusercontent.com/101639308/214195394-0f55db86-5a2c-4fb5-987f-099d6c37f63f.png)

**Comment by liedekef** [comment]
As the doc specifies:
"Remark: multibooking mails are only sent for the initial booking, so if afterwards you mail people for approval or payment notifications, those are individual mails."

**Comment by sonalvrioss-svyatos** [comment]
I don't understand. The initial booking mail should come after the confirmation email right? 

If this is the way it works, it means that the confirmation email setting is useless for multi-booking. Then, how can I ensure the email that applicants use to register for the event is the actual email and not some disposable email that is trying to spam the form?

**Comment by liedekef** [comment]
There are 2 types of confirmation:

- user confirmation (which will send only 1 mail, so the user can confirm)
- normal confirmation (if event booking confirmation is required), which is 1 per event if the user confirmed and auto-approve is on.

The user confirmation sends only 1 mail, but is/should be multibooking-compatible (per the "Multibooking mails" instructions on https://www.e-dynamics.be/wordpress/category/documentation/6-shortcodes/eme_add_multibooking_form/ ). The subject is always very hard to set in those cases, but you can configure a more generic "user confirmation required" subject in your events (or in general). Currently, after the user confirmed, the confirmed-mail is per event. At that time, I no longer look at the multi-booking specs anymore (has always been the case, I went back to version 2.3.0 to verify). I could check there for multibooking, but that's currently a change in the way it works (and is documented), so that's more of a feature request ...
