### ISSUE TITLE
Warning: Undefined variable $res in /wp-content/plugins/events-made-easy/eme-rsvp.php on line 3191

### ISSUE THREAD

**Issue by WXQ8NPb5TrbDNqzywcxF** [liedekef/events-made-easy#369]
**Describe the bug**
I don't know wich setting i've changed,  but I have this error on event description page
Warning: Undefined variable $res in*/wp-content/plugins/events-made-easy/eme-rsvp.php on line 3191

**To Reproduce**
Go to an event page with no reservation done

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version: 7
EME version: 2.4.16

![2023-12-04 15_37_14-Marche et Ateliers – Implication parentale](https://github.com/liedekef/events-made-easy/assets/81836762/6e9cf568-bb97-4abb-b270-7dbf3db7ae53)

**Comment by liedekef** [comment]
This is a php warning, you should configure php (and/or wordpress) so that it doesn't show php warnings on the website (but only in the logfile).
However, this is the fix:
https://github.com/liedekef/events-made-easy/commit/5d936c8590cf04486fce1e0450ffde89dd553e1a

Next to that: php 7 is not possible with EME, should be php 8 (php 7 is end of life since the beginning of this year and EME uses specific php 8 functionality).
