### ISSUE TITLE
Bug with PHP 8.2

### ISSUE THREAD

**Issue by RoundAboutWEB** [liedekef/events-made-easy#383]
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /html/wordpress/wp-content/plugins/events-made-easy-main/eme-events.php on line 3943

PHP Deprecated:  substr_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /html/wordpress/wp-content/plugins/events-made-easy-main/eme-events.php on line 3942

**Comment by liedekef** [comment]
which version of EME are you using?

**Comment by liedekef** [comment]
Next to that: please specify which placeholder is triggering this

**Comment by liedekef** [comment]
While waiting for an answer, I already updated the code to better take into account possible null-values for replacement of a placeholder (also possible for images that no longer exist).

**Comment by liedekef** [comment]
EME is still supported (and the security breach is long closed, about a year ago ...). But no problem, you're free to use any plugin of choice.

**Comment by RoundAboutWEB** [comment]
That is not correct. EME is no longer offered at https://wordpress.org/plugins/ because it is no longer verified and therefore does not fulfil the WordPress security requirements for the plugin. I have therefore opted for a different solution.

**Comment by liedekef** [comment]
No, EME is no longer offered not because of the security issue but because they have imposed new coding standards that I believe to be too strict (and not logical). The security issue is long fixed but since they refuse the plugin (because of the coding standards), they refuse to release the fixed version. This is something unseen in the security world (and as somewhat of a security expert I know what I'm talking about): they leave their users open to a known security issue.
I've had several discussions with them but to no avail. So I've abandoned wordpress.org and stopped trying to get it right.
Other plugins suffered the same issue (even a security scan plugin like WP Cerber, read about that here: https://wpcerber.com/cerber-sw-repository/ )
