### ISSUE TITLE
Warning: Undefined variable

### ISSUE THREAD

**Issue by Navegola** [liedekef/events-made-easy#53]
Warning: Undefined variable $wp in /homepages/25/d4296777296/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 1305

Warning: Attempt to read property "request" on null in /homepages/25/d4296777296/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 1305

In this shortcode:     [eme_events  scope=this_week]

**Comment by liedekef** [comment]
Confirmed, this fixes it:
https://github.com/liedekef/events-made-easy/commit/e92f292c2101c11f2fbded54bdd9e48627207b46

**Comment by JosiahCarberry** [comment]
Of course, these messages are visible ONLY in a test environment. I don't deploy updates to production if such errors are noted and I don't enable the display of such message in production.

In any case, I have the latest version of EME installed and the problem is not fixed. I regret an issue being closed when it is not yet available to users.

**Comment by liedekef** [comment]
An issue is closed once the bug is fixed in the code. You'll just need to wait for the next release or implement the one-liner fix yourself.

**Comment by Navegola** [comment]
Hello Franky,

Fixed the bug
Thank you very much for this quick solution.

Navegola
