### ISSUE TITLE
Conflicting permalink settings

### ISSUE THREAD

**Issue by JosiahCarberry** [liedekef/events-made-easy#56]
I now get the following message in the EME backend:

The EME SEO permalink settings are conflicting with an existing page (the permalink setting for either events, locations or categories is identical with the permalink of another WordPress page). This might cause problems rendering either events or that page. Please resolve the conflict by either changing your EME SEO permalink settings or the permalink of the conflicting page.
The conflicting page can be edited [here]).

The conflicting page is "Locations" page (according to the link to the page to be edited).

I am at a complete loss to understand how to identify the conflict, what might be in conflict, whether it concerns a conflict with a Wordpress setting, with an SEO (Yoast) setting, or yet something else.

Any guidance regarding how to figure what, exactly, is in conflict and what field in EME needs to be changed would be highly appreciated.

**Comment by liedekef** [comment]
EME has permalink settings (for events, locations, ...) and also other WP pages do. If those pages use the same permalinks as in EME, this *might* pose a problem (I do my best to let EME "win" for specific url's, but it is not a guarantee).
In this, case since it seems to be a page called "Locations", I'm guessing that page has the wordpress permalink "locations", while EME locations also have this permalink:
![image](https://user-images.githubusercontent.com/75667/216070081-2c6dcb43-ccf5-44e3-a514-3815c29040de.png)

So either change the permalink of that page, or change the EME settings.

**Comment by JosiahCarberry** [comment]
Thanks for this clarification.
