### ISSUE TITLE
Issues with mailing to unpaid bookings

### ISSUE THREAD

**Issue by TommieNL** [liedekef/events-made-easy#595]
Hello!

I have the following issue: I'm trying to send a specific email (see below) to people who registered but failed to complete a payment.

Here's what I'm doing:

1.     Go to mail management
2.     Select the event
3.     Choose booking emails (Boeking mails)
4.     Select unpaid bookings
5.     Select a subject and email

**Then I send a test email.** I think I chose a test email for someone who also booked.

But the mail is received with codes like: #_PAYMENT_URL & #_EVENTNAME. 

I would like to include the payment URL here for the specific booking. What am i doing wrong?

**Comment by liedekef** [comment]
The preview for event mails works only partially (since you select a person and not a booking, the payment url can't be rendered). The #_EVENTNAME however works as expected (just tested), but you need to make sure to select an event.
Also, there is a small php warning there (only when sending the test), which is fixed by this oneliner:
https://github.com/liedekef/events-made-easy/commit/025ade7cc419db80a9d1ef4c16bd4cef67a98608
Next to that: make sure to be on the last version as well (2.4.49 at the moment)
