### ISSUE TITLE
Revise error message in "eme-locations.php" for error while importing

### ISSUE THREAD

**Issue by KRider92** [liedekef/events-made-easy#621]
Hi,

While using eme on our website I found that the error message when importing events is very unclear, as to _which_ required columns are missing from an import file.
Hence I propose to revise the error message from
`$result = __( 'Not all required fields present.', 'events-made-easy' );`
to
`$result = __( 'Error! Required fields location_name and location_address1 not present in import file.', 'events-made-easy' );`

This would make it very easy to pinpoint what's going wrong without looking into the code itself.

Thanks!

**Comment by KRider92** [comment]
By the way, same would go for "eme-events.php", though I haven't imported anything on that side yet.
`$result = __( 'Not all required fields present.', 'events-made-easy' );`
would imho be better worded with
`$result = __( 'Error! Required field event_name not present in import file.', 'events-made-easy' );`

**Comment by liedekef** [comment]
In fact for locations there should be 3 columns (identical to those mentioned in the doc, it was an old thing that it only requires 2 fields). And as you need to read the doc to create the CSV files, I refer to that for the required fields: https://www.e-dynamics.be/wordpress/csv-import-events-and-locations/
Doing this hardcoded in the code is not the best idea, since it can change over time and then translators would need to change their part too. Anyway, I've marked it as bold for import in the doc.
