### ISSUE TITLE
Membership properties does not work anymore

### ISSUE THREAD

**Issue by YannickGutmann** [liedekef/events-made-easy#678]
**Describe the bug**
My membership settings do not appear to be applied correctly. When I view the membership settings through WordPress, they no longer match the original configuration or the current values stored in the database under the 'wp_eme_memberships' table in the 'properties' field. Additionally, the settings cannot be modified in WordPress, as the save button does not function, and the settings stored in the database are not being applied.

**To Reproduce**
1. Go to Events Made Easy > Memberships
2. Open a Membership
3. Set your settings (they not match with the stored values in the database)
4. Try to save
5. Save button has no reaction

**Screenshots**
Example: ![image](https://github.com/user-attachments/assets/40bc2b44-99c4-48ca-a3a0-bef0c7079e47)

**Version info**
PHP version: 8.3
EME version: 2.5.18

**Comment by liedekef** [comment]
Not sure about the values (the captcha name changed, so the value in your properties will get removed), but there was a hidden field being required and that blocked the update.
That has been fixed by the just-released version, so try that first :-)
The captcha should be rechecked. Normally I take the old/new properties name into account, but once you save it, it will surely be correct.
